/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as PortalIndexRouteImport } from './routes/_portal.index'
import { Route as PortalQuemEscreveRouteImport } from './routes/_portal.quem-escreve'
import { Route as PortalBuscaRouteImport } from './routes/_portal.busca'
import { Route as PortalAnuncieRouteImport } from './routes/_portal.anuncie'
import { Route as PortalNoticiaSlugRouteImport } from './routes/_portal.noticia.$slug'
import { Route as PortalEditoriaSlugRouteImport } from './routes/_portal.editoria.$slug'

const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalQuemEscreveRoute = PortalQuemEscreveRouteImport.update({
  id: '/quem-escreve',
  path: '/quem-escreve',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBuscaRoute = PortalBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAnuncieRoute = PortalAnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNoticiaSlugRoute = PortalNoticiaSlugRouteImport.update({
  id: '/noticia/$slug',
  path: '/noticia/$slug',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEditoriaSlugRoute = PortalEditoriaSlugRouteImport.update({
  id: '/editoria/$slug',
  path: '/editoria/$slug',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PortalIndexRoute
  '/anuncie': typeof PortalAnuncieRoute
  '/busca': typeof PortalBuscaRoute
  '/quem-escreve': typeof PortalQuemEscreveRoute
  '/editoria/$slug': typeof PortalEditoriaSlugRoute
  '/noticia/$slug': typeof PortalNoticiaSlugRoute
}
export interface FileRoutesByTo {
  '/anuncie': typeof PortalAnuncieRoute
  '/busca': typeof PortalBuscaRoute
  '/quem-escreve': typeof PortalQuemEscreveRoute
  '/': typeof PortalIndexRoute
  '/editoria/$slug': typeof PortalEditoriaSlugRoute
  '/noticia/$slug': typeof PortalNoticiaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_portal': typeof PortalRouteWithChildren
  '/_portal/anuncie': typeof PortalAnuncieRoute
  '/_portal/busca': typeof PortalBuscaRoute
  '/_portal/quem-escreve': typeof PortalQuemEscreveRoute
  '/_portal/': typeof PortalIndexRoute
  '/_portal/editoria/$slug': typeof PortalEditoriaSlugRoute
  '/_portal/noticia/$slug': typeof PortalNoticiaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anuncie'
    | '/busca'
    | '/quem-escreve'
    | '/editoria/$slug'
    | '/noticia/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/anuncie'
    | '/busca'
    | '/quem-escreve'
    | '/'
    | '/editoria/$slug'
    | '/noticia/$slug'
  id:
    | '__root__'
    | '/_portal'
    | '/_portal/anuncie'
    | '/_portal/busca'
    | '/_portal/quem-escreve'
    | '/_portal/'
    | '/_portal/editoria/$slug'
    | '/_portal/noticia/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/': {
      id: '/_portal/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/quem-escreve': {
      id: '/_portal/quem-escreve'
      path: '/quem-escreve'
      fullPath: '/quem-escreve'
      preLoaderRoute: typeof PortalQuemEscreveRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/busca': {
      id: '/_portal/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof PortalBuscaRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/anuncie': {
      id: '/_portal/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof PortalAnuncieRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/noticia/$slug': {
      id: '/_portal/noticia/$slug'
      path: '/noticia/$slug'
      fullPath: '/noticia/$slug'
      preLoaderRoute: typeof PortalNoticiaSlugRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/editoria/$slug': {
      id: '/_portal/editoria/$slug'
      path: '/editoria/$slug'
      fullPath: '/editoria/$slug'
      preLoaderRoute: typeof PortalEditoriaSlugRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalAnuncieRoute: typeof PortalAnuncieRoute
  PortalBuscaRoute: typeof PortalBuscaRoute
  PortalQuemEscreveRoute: typeof PortalQuemEscreveRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalEditoriaSlugRoute: typeof PortalEditoriaSlugRoute
  PortalNoticiaSlugRoute: typeof PortalNoticiaSlugRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAnuncieRoute: PortalAnuncieRoute,
  PortalBuscaRoute: PortalBuscaRoute,
  PortalQuemEscreveRoute: PortalQuemEscreveRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalEditoriaSlugRoute: PortalEditoriaSlugRoute,
  PortalNoticiaSlugRoute: PortalNoticiaSlugRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
