/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NewsSitemapDotxmlRouteImport } from './routes/news-sitemap[.]xml'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PortalIndexRouteImport } from './routes/_portal.index'
import { Route as PortalQuemEscreveRouteImport } from './routes/_portal.quem-escreve'
import { Route as PortalColunistasRouteImport } from './routes/_portal.colunistas'
import { Route as PortalBuscaRouteImport } from './routes/_portal.busca'
import { Route as PortalAnuncieRouteImport } from './routes/_portal.anuncie'
import { Route as AuthenticatedMinhasColunasRouteImport } from './routes/_authenticated/minhas-colunas'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as PortalVideosSectionRouteImport } from './routes/_portal.videos.$section'
import { Route as PortalNoticiaSlugRouteImport } from './routes/_portal.noticia.$slug'
import { Route as PortalEditoriaSlugRouteImport } from './routes/_portal.editoria.$slug'
import { Route as PortalColunistaSlugRouteImport } from './routes/_portal.colunista.$slug'
import { Route as PortalColunaSlugRouteImport } from './routes/_portal.coluna.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as PortalYearMonthDaySlugRouteImport } from './routes/_portal.$year.$month.$day.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSitemapDotxmlRoute = NewsSitemapDotxmlRouteImport.update({
  id: '/news-sitemap.xml',
  path: '/news-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalQuemEscreveRoute = PortalQuemEscreveRouteImport.update({
  id: '/quem-escreve',
  path: '/quem-escreve',
  getParentRoute: () => PortalRoute,
} as any)
const PortalColunistasRoute = PortalColunistasRouteImport.update({
  id: '/colunistas',
  path: '/colunistas',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBuscaRoute = PortalBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAnuncieRoute = PortalAnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => PortalRoute,
} as any)
const AuthenticatedMinhasColunasRoute =
  AuthenticatedMinhasColunasRouteImport.update({
    id: '/minhas-colunas',
    path: '/minhas-colunas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalVideosSectionRoute = PortalVideosSectionRouteImport.update({
  id: '/videos/$section',
  path: '/videos/$section',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNoticiaSlugRoute = PortalNoticiaSlugRouteImport.update({
  id: '/noticia/$slug',
  path: '/noticia/$slug',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEditoriaSlugRoute = PortalEditoriaSlugRouteImport.update({
  id: '/editoria/$slug',
  path: '/editoria/$slug',
  getParentRoute: () => PortalRoute,
} as any)
const PortalColunistaSlugRoute = PortalColunistaSlugRouteImport.update({
  id: '/colunista/$slug',
  path: '/colunista/$slug',
  getParentRoute: () => PortalRoute,
} as any)
const PortalColunaSlugRoute = PortalColunaSlugRouteImport.update({
  id: '/coluna/$slug',
  path: '/coluna/$slug',
  getParentRoute: () => PortalRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalYearMonthDaySlugRoute = PortalYearMonthDaySlugRouteImport.update({
  id: '/$year/$month/$day/$slug',
  path: '/$year/$month/$day/$slug',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PortalIndexRoute
  '/auth': typeof AuthRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/mcp': typeof McpRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/minhas-colunas': typeof AuthenticatedMinhasColunasRoute
  '/anuncie': typeof PortalAnuncieRoute
  '/busca': typeof PortalBuscaRoute
  '/colunistas': typeof PortalColunistasRoute
  '/quem-escreve': typeof PortalQuemEscreveRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/coluna/$slug': typeof PortalColunaSlugRoute
  '/colunista/$slug': typeof PortalColunistaSlugRoute
  '/editoria/$slug': typeof PortalEditoriaSlugRoute
  '/noticia/$slug': typeof PortalNoticiaSlugRoute
  '/videos/$section': typeof PortalVideosSectionRoute
  '/$year/$month/$day/$slug': typeof PortalYearMonthDaySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof PortalIndexRoute
  '/auth': typeof AuthRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/mcp': typeof McpRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/minhas-colunas': typeof AuthenticatedMinhasColunasRoute
  '/anuncie': typeof PortalAnuncieRoute
  '/busca': typeof PortalBuscaRoute
  '/colunistas': typeof PortalColunistasRoute
  '/quem-escreve': typeof PortalQuemEscreveRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/coluna/$slug': typeof PortalColunaSlugRoute
  '/colunista/$slug': typeof PortalColunistaSlugRoute
  '/editoria/$slug': typeof PortalEditoriaSlugRoute
  '/noticia/$slug': typeof PortalNoticiaSlugRoute
  '/videos/$section': typeof PortalVideosSectionRoute
  '/$year/$month/$day/$slug': typeof PortalYearMonthDaySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_portal': typeof PortalRouteWithChildren
  '/auth': typeof AuthRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/mcp': typeof McpRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/minhas-colunas': typeof AuthenticatedMinhasColunasRoute
  '/_portal/anuncie': typeof PortalAnuncieRoute
  '/_portal/busca': typeof PortalBuscaRoute
  '/_portal/colunistas': typeof PortalColunistasRoute
  '/_portal/quem-escreve': typeof PortalQuemEscreveRoute
  '/_portal/': typeof PortalIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_portal/coluna/$slug': typeof PortalColunaSlugRoute
  '/_portal/colunista/$slug': typeof PortalColunistaSlugRoute
  '/_portal/editoria/$slug': typeof PortalEditoriaSlugRoute
  '/_portal/noticia/$slug': typeof PortalNoticiaSlugRoute
  '/_portal/videos/$section': typeof PortalVideosSectionRoute
  '/_portal/$year/$month/$day/$slug': typeof PortalYearMonthDaySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/feed.xml'
    | '/mcp'
    | '/news-sitemap.xml'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/minhas-colunas'
    | '/anuncie'
    | '/busca'
    | '/colunistas'
    | '/quem-escreve'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/coluna/$slug'
    | '/colunista/$slug'
    | '/editoria/$slug'
    | '/noticia/$slug'
    | '/videos/$section'
    | '/$year/$month/$day/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/feed.xml'
    | '/mcp'
    | '/news-sitemap.xml'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/minhas-colunas'
    | '/anuncie'
    | '/busca'
    | '/colunistas'
    | '/quem-escreve'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/coluna/$slug'
    | '/colunista/$slug'
    | '/editoria/$slug'
    | '/noticia/$slug'
    | '/videos/$section'
    | '/$year/$month/$day/$slug'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_portal'
    | '/auth'
    | '/feed.xml'
    | '/mcp'
    | '/news-sitemap.xml'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/minhas-colunas'
    | '/_portal/anuncie'
    | '/_portal/busca'
    | '/_portal/colunistas'
    | '/_portal/quem-escreve'
    | '/_portal/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_portal/coluna/$slug'
    | '/_portal/colunista/$slug'
    | '/_portal/editoria/$slug'
    | '/_portal/noticia/$slug'
    | '/_portal/videos/$section'
    | '/_portal/$year/$month/$day/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  AuthRoute: typeof AuthRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  McpRoute: typeof McpRoute
  NewsSitemapDotxmlRoute: typeof NewsSitemapDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-sitemap.xml': {
      id: '/news-sitemap.xml'
      path: '/news-sitemap.xml'
      fullPath: '/news-sitemap.xml'
      preLoaderRoute: typeof NewsSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/': {
      id: '/_portal/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/quem-escreve': {
      id: '/_portal/quem-escreve'
      path: '/quem-escreve'
      fullPath: '/quem-escreve'
      preLoaderRoute: typeof PortalQuemEscreveRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/colunistas': {
      id: '/_portal/colunistas'
      path: '/colunistas'
      fullPath: '/colunistas'
      preLoaderRoute: typeof PortalColunistasRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/busca': {
      id: '/_portal/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof PortalBuscaRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/anuncie': {
      id: '/_portal/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof PortalAnuncieRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_authenticated/minhas-colunas': {
      id: '/_authenticated/minhas-colunas'
      path: '/minhas-colunas'
      fullPath: '/minhas-colunas'
      preLoaderRoute: typeof AuthenticatedMinhasColunasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/videos/$section': {
      id: '/_portal/videos/$section'
      path: '/videos/$section'
      fullPath: '/videos/$section'
      preLoaderRoute: typeof PortalVideosSectionRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/noticia/$slug': {
      id: '/_portal/noticia/$slug'
      path: '/noticia/$slug'
      fullPath: '/noticia/$slug'
      preLoaderRoute: typeof PortalNoticiaSlugRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/editoria/$slug': {
      id: '/_portal/editoria/$slug'
      path: '/editoria/$slug'
      fullPath: '/editoria/$slug'
      preLoaderRoute: typeof PortalEditoriaSlugRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/colunista/$slug': {
      id: '/_portal/colunista/$slug'
      path: '/colunista/$slug'
      fullPath: '/colunista/$slug'
      preLoaderRoute: typeof PortalColunistaSlugRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/coluna/$slug': {
      id: '/_portal/coluna/$slug'
      path: '/coluna/$slug'
      fullPath: '/coluna/$slug'
      preLoaderRoute: typeof PortalColunaSlugRouteImport
      parentRoute: typeof PortalRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/$year/$month/$day/$slug': {
      id: '/_portal/$year/$month/$day/$slug'
      path: '/$year/$month/$day/$slug'
      fullPath: '/$year/$month/$day/$slug'
      preLoaderRoute: typeof PortalYearMonthDaySlugRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMinhasColunasRoute: typeof AuthenticatedMinhasColunasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMinhasColunasRoute: AuthenticatedMinhasColunasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PortalRouteChildren {
  PortalAnuncieRoute: typeof PortalAnuncieRoute
  PortalBuscaRoute: typeof PortalBuscaRoute
  PortalColunistasRoute: typeof PortalColunistasRoute
  PortalQuemEscreveRoute: typeof PortalQuemEscreveRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalColunaSlugRoute: typeof PortalColunaSlugRoute
  PortalColunistaSlugRoute: typeof PortalColunistaSlugRoute
  PortalEditoriaSlugRoute: typeof PortalEditoriaSlugRoute
  PortalNoticiaSlugRoute: typeof PortalNoticiaSlugRoute
  PortalVideosSectionRoute: typeof PortalVideosSectionRoute
  PortalYearMonthDaySlugRoute: typeof PortalYearMonthDaySlugRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAnuncieRoute: PortalAnuncieRoute,
  PortalBuscaRoute: PortalBuscaRoute,
  PortalColunistasRoute: PortalColunistasRoute,
  PortalQuemEscreveRoute: PortalQuemEscreveRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalColunaSlugRoute: PortalColunaSlugRoute,
  PortalColunistaSlugRoute: PortalColunistaSlugRoute,
  PortalEditoriaSlugRoute: PortalEditoriaSlugRoute,
  PortalNoticiaSlugRoute: PortalNoticiaSlugRoute,
  PortalVideosSectionRoute: PortalVideosSectionRoute,
  PortalYearMonthDaySlugRoute: PortalYearMonthDaySlugRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  AuthRoute: AuthRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  McpRoute: McpRoute,
  NewsSitemapDotxmlRoute: NewsSitemapDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
